### 模式识别作业

针对iris数据集，编写k近邻树进行类别预测

In [7]:
from sklearn.datasets import load_iris
import numpy as np

读取数据

In [17]:

iris = load_iris()
x = iris.data
y= iris.target

random_index=np.random.choice(x.shape[0],x.shape[0],replace=False)
x=x[random_index]
y=y[random_index]
print(x.shape)

(150, 4)


In [24]:
#归一化
x_max=np.max(x,axis=0)
x_min=np.min(x,axis=0)
x=(x-x_min)/(x_max-x_min)
print(x[:5,:])

[[0.41666667 0.29166667 0.49152542 0.45833333]
 [0.52777778 0.08333333 0.59322034 0.58333333]
 [0.25       0.625      0.08474576 0.04166667]
 [0.33333333 0.16666667 0.47457627 0.41666667]
 [0.08333333 0.5        0.06779661 0.04166667]]


In [27]:
#分为样本和预测
x_sample=x[:120,:]
y_sample=y[:120]
x_pre=x[120:,:]
y_pre=y[120:]

In [32]:
#定义一个预测方法，输入样本和需要预测的数据，以及k
def prediction(x_sample,y_sample,x_pre,k):
    #计算x_pre到样本的距离
    distance=(x_sample-x_pre).sum()

    print(distance)

prediction(x_sample,y_sample,x_pre[0,:],5)

[[ 0.08333333  0.08333333 -0.01694915 -0.04166667]
 [ 0.19444444 -0.125       0.08474576  0.08333333]
 [-0.08333333  0.41666667 -0.42372881 -0.45833333]
 [ 0.         -0.04166667 -0.03389831 -0.08333333]
 [-0.25        0.29166667 -0.44067797 -0.45833333]
 [-0.16666667  0.25       -0.42372881 -0.5       ]
 [-0.02777778  0.375      -0.42372881 -0.375     ]
 [-0.16666667  0.45833333 -0.44067797 -0.5       ]
 [ 0.05555556  0.20833333  0.03389831 -0.04166667]
 [-0.13888889  0.375      -0.40677966 -0.375     ]
 [ 0.41666667  0.29166667  0.11864407  0.04166667]
 [ 0.22222222  0.          0.15254237  0.08333333]
 [-0.16666667  0.25       -0.42372881 -0.45833333]
 [ 0.33333333  0.20833333  0.16949153  0.16666667]
 [ 0.02777778  0.20833333  0.08474576  0.08333333]
 [-0.30555556  0.20833333 -0.45762712 -0.45833333]
 [-0.02777778  0.58333333 -0.45762712 -0.375     ]
 [ 0.02777778  0.125       0.15254237  0.29166667]
 [ 0.16666667  0.20833333  0.10169492  0.04166667]
 [ 0.08333333  0.08333333  0.18