### 模式识别作业

针对iris数据集，编写k近邻树进行类别预测

In [7]:
from sklearn.datasets import load_iris
import numpy as np

读取数据

In [17]:

iris = load_iris()
x = iris.data
y= iris.target

random_index=np.random.choice(x.shape[0],x.shape[0],replace=False)
x=x[random_index]
y=y[random_index]
print(x.shape)

(150, 4)


In [24]:
#归一化
x_max=np.max(x,axis=0)
x_min=np.min(x,axis=0)
x=(x-x_min)/(x_max-x_min)
print(x[:5,:])

[[0.41666667 0.29166667 0.49152542 0.45833333]
 [0.52777778 0.08333333 0.59322034 0.58333333]
 [0.25       0.625      0.08474576 0.04166667]
 [0.33333333 0.16666667 0.47457627 0.41666667]
 [0.08333333 0.5        0.06779661 0.04166667]]


In [ ]:
#分为样本和预测
x_sample=x[:120,:]
y_sample=y[:120]
x_pre=x[120:,:]
y_pre=y[120:,:]

In [ ]:
#定义一个预测方法，输入样本和需要预测的数据，以及k
def prediction(x_sample,y_sample,x_pre,k):
    #计算x_pre到样本的距离
    distance=np.power(x_sample,2)-np.power(y_sample,2)
    print(distance)

prediction(x_sample,y_sample,x_pre,5)